export const privacyPolicy = [
  { id: "introduction", title: "About this policy", paragraphs: ["This policy describes how Puraitmaad handles information provided through this website and its service-request form.", "Requests are processed on our server and sent through Resend to Puraitmaad's configured email inbox. The website does not currently include analytics or marketing tracking."] },
  { id: "information", title: "Information you may provide", paragraphs: ["The request form asks for your name, general location or area and a description of what needs to be handled. At least one phone / WhatsApp number or email is required; both may be supplied. Preferred date and time are optional preferences, not confirmed appointments."], items: ["Name", "Phone / WhatsApp number, when supplied", "Email address, when supplied", "Location / Area", "Request description", "Preferred date, when supplied", "Preferred time, when supplied", "Optional service context when you follow a service-specific request link"], note: "Please leave out passwords, access or alarm codes, financial details, information about valuables and exact street addresses. Start with the general area and practical need." },
  { id: "uses", title: "How information is used", paragraphs: ["We use your request to understand what needs doing, respond through the contact details you provide and discuss the relevant scope and practical arrangements."], items: ["Review and respond to your request", "Clarify location, requirements and timing", "Coordinate agreed work and communicate relevant updates", "Maintain necessary correspondence and business records where appropriate"] },
  { id: "marketing", title: "Marketing", paragraphs: ["Sending a request does not automatically subscribe you to marketing communications. The website does not currently offer a newsletter subscription."] },
  { id: "sharing", title: "Sharing and delivery", paragraphs: ["Puraitmaad does not sell personal information. Resend processes the submitted request for email delivery, and the receiving email service handles the resulting correspondence.", "Hosting may involve technical request information. Details needed to coordinate agreed work may be shared with relevant service providers; sharing should be limited to the information reasonably needed for that purpose."] },
  { id: "retention", title: "Email correspondence and retention", paragraphs: ["Requests may remain in email correspondence. The form does not add request records to a database. Delivery uses a provider idempotency key to reduce duplicate sends; this is separate from a business records system.", "No fixed retention period has been established. Retention arrangements remain pending business and professional legal review."] },
  { id: "security", title: "Handling information carefully", paragraphs: ["The request system uses server-side validation, bounded inputs and escaped email content. Email delivery configuration stays on the server.", "These measures do not guarantee complete security of internet transmission or storage. Please avoid unnecessary sensitive information when describing a request."] },
  { id: "privacy-and-discretion", title: "Privacy and discretion", paragraphs: ["Home and personal requests can involve private details. Our approach is to ask for what is needed, communicate thoughtfully and limit unnecessary disclosure while coordinating agreed work.", "Access arrangements and any further information needed should be discussed for the specific request. This approach is not a blanket confidentiality or security guarantee."] },
  { id: "privacy-questions", title: "Privacy questions", paragraphs: ["You can raise a privacy question through the website request form. Describe the concern without including passwords or other sensitive details."] },
  { id: "updates", title: "Policy updates", paragraphs: ["This policy should be reviewed as the website and operating arrangements change. The content needs business and professional legal review before the final launch."] },
];
